version: "3.8"

services:
  documents-service:
    build:
      context: ./awawawiwa-documents-services
      dockerfile: Dockerfile
    container_name: documents-services
    ports:
      - "8080:8080"
    env_file: 
      - .env
    restart: always
    networks:
      - quiz-network

networks:
  quiz-network:
    external: true